### ISSUE TITLE
Python: install

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MD#2]
@AnnaRybakovaT    This issue for describing installation of Python for you.

This depends on some details of your computer.  

First, do you already have Python on your computer?  How to know?
Open git bash terminal  (which I believe you already have), and type
`python --version`.

If this returns a version,  please mention what it is in comment.

If this says you don't have python  (`Python was not found`), then
tell me that,  and also, what operating system and version do you have on your computer.
For instance, I would answer `Windows 10`  as the operating system and version of the computer I am on at the moment.

With this info, I will aim to get Python installation instructions for you.

**Comment by AnnaRybakovaT** [comment]
> what operating system and version

Dear Jim,
I have Windows 7.
I am almost sure that I don't have Python on my computer. If I did everything correct, Git bash has the same opinion:
![изображение](https://user-images.githubusercontent.com/74726889/147689022-d5b7648c-a782-4e7a-9556-8c1a4eae3323.png)

**Comment by funderburkjim** [comment]
My computers have Windows 10.  Since you have Windows 7, Python installation seems to require one more piece of information: Do you have '32 bit' or '64 bit' Windows.

This link describes how to know whether your are '32 bit' or '64 bit' windows.

**Comment by funderburkjim** [comment]
Tell me whether your computer is 32 or 64 bit.  Here is the link: https://www.solveyourtech.com/do-i-have-32-bit-or-64-bit-windows-7/.

**Comment by AnnaRybakovaT** [comment]
Dear Jim,
I have '64 bit' Windows. Maybe this data will be useful as well:
![изображение](https://user-images.githubusercontent.com/74726889/147698338-0511e101-20cc-4fad-8373-121117d2f2f7.png)

**Comment by funderburkjim** [comment]
@AnnaRybakovaT  --  Because you have Windows 7, you must use a version 3.8x of Python  (Versions 3.9 and 3.10 are said not to work on Windows 7). For reference, my current system has Python 3.9.1.  Version 3.8x should be fine.

I recommend you to look at the 10-minute video https://www.youtube.com/watch?v=WNv2-rJiQFA.    This is not exactly what you will do, but it will be close.  Here are
3 steps.

## Step 1: Download the installer for Python 3.8.10
Go to this URL: https://www.python.org/downloads/windows/
Scroll down to 
![image](https://user-images.githubusercontent.com/6393033/147720856-3811196d-a1c4-419c-ad06-3ac22d708cb4.png)

and click where indicated.  This will download the installer - put it into your downloads folder.
![image](https://user-images.githubusercontent.com/6393033/147720969-186c042f-c995-445a-be79-5d8ef7c86896.png)

## Step 2: Run installer
Double-click on the installer. You'll see:
![image](https://user-images.githubusercontent.com/6393033/147721092-ca741688-00b8-4233-ae70-a7c1bc794982.png)

(Your location will differ from mine , I suggest you make a note of the location).
Also suggest you select the 'Add Python 3.8 to PATH'.
Then, click 'Install now'.  After a bit, you should see:  

![image](https://user-images.githubusercontent.com/6393033/147721197-4f2673a0-d626-4c04-87ee-6aff31fe76b8.png)

You can look at the online tutorial or documentation  (maybe save the links for possible
later use).  Then click Close.

##  Step 3: Try with Git Bash.
Open a new Git Bash Terminal.
and enter `python -V` 
If this works, you're ready to go.

**Comment by AnnaRybakovaT** [comment]
Dear Jim, 
Thanks to your guidance, it has done. 

![изображение](https://user-images.githubusercontent.com/74726889/147779240-b628be25-b295-43b9-a145-f3e1daf7de55.png)

**Comment by funderburkjim** [comment]
Hurray!
Next steps will be writing some simple programs that read the lines in a text file,
do something with the lines, and write out new lines into another text file.

Since we have a specific objective in mind (the `MD - Devanagari and IAST comparison` issue mentioned above),  that will be the focus of next steps. Stay tuned!

**Comment by gasyoun** [comment]
So good to see this duo come live. @funderburkjim when is your first Sanskrit class to come?

**Comment by funderburkjim** [comment]
Usha has already begun the class. We are using Hitopadesha.
